import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import ConsoleLogger from '@/components/general/Consolelogger';
import LenisWrapper from '@/components/general/LenisWrapper';
import { Toaster } from 'sonner';
import ServiceWorkerRegistration from '@/components/general/ServiceWorkerRegistration';

import { ThemeProvider } from 'next-themes';

const inter = Inter({
	weight: ['400', '500', '600', '800'],
	variable: '--inter',
	subsets: ['latin'],
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Web0 Admin',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${inter.variable}`}>
				<ConsoleLogger />
				<ServiceWorkerRegistration />
				<LenisWrapper>
					<ThemeProvider>
						{children}
						<Toaster />
					</ThemeProvider>
				</LenisWrapper>
			</body>
		</html>
	);
}
