import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import ConsoleLogger from '@/components/General/Consolelogger';
import Layout from '@/components/General/Layout';
import LenisWrapper from '@/components/General/LenisWrapper';

const inter = Inter({
	weight: ['400', '500', '600', '800'],
	variable: '--inter',
	subsets: ['latin'],
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Web0 Admin',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable}`}>
				<ConsoleLogger />
				<LenisWrapper>
					<Layout>{children}</Layout>
				</LenisWrapper>
			</body>
		</html>
	);
}
