version: '3'

services:
  db:
    image: postgres:13.0
    env_file: ./judge0.conf
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis:6.0
    command:
      ['bash', '-c', 'docker-entrypoint.sh --requirepass "$$REDIS_PASSWORD"']
    env_file: ./judge0.conf
    volumes:
      - redis-data:/data
    restart: always

  judge0:
    image: judge0/judge0:1.13.1
    env_file: ./judge0.conf
    ports:
      - '2359:2358'
    volumes:
      - ./judge0-additional-scripts:/judge0/additional-scripts
    privileged: true
    depends_on:
      - db
      - redis
    restart: always

volumes:
  postgres-data:
  redis-data:
